# Generated by Django 4.2.5 on 2023-10-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("filer", "0017_image__transparent")]

    operations = [
        migrations.CreateModel(
            name="RefreshFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="filer.file"
                    ),
                ),
            ],
        )
    ]
